package tech.fiap.project.infra.exception;

import tech.fiap.project.domain.entity.Person;

import static org.junit.jupiter.api.Assertions.*;
class PersonNotFoundExceptionTest {
//    @org.junit.jupiter.api.Test
//    void testPersonNotFoundException() {
//        PersonNotFoundException result = new PersonNotFoundException("1");
//        assertEquals("Pessoa com id [1] não encontrada", result.getMessage());
//        assertEquals(org.springframework.http.HttpStatus.NOT_FOUND, result.getHttpStatusCode());
//    }
//
//    @org.junit.jupiter.api.Test
//    void testPersonNotFoundException2() {
//        Person person = new Person();
//        person.setId(1L);
//        PersonNotFoundException result = new PersonNotFoundException(person);
//        assertEquals("Pessoa com id [1] não encontrada", result.getMessage());
//        assertNotNull(result.getMetadata());
//        assertEquals(org.springframework.http.HttpStatus.NOT_FOUND, result.getHttpStatusCode());
//    }
//
//    @org.junit.jupiter.api.Test
//    void testPersonNotFoundException3() {
//        PersonNotFoundException result = new PersonNotFoundException(java.util.Optional.of("email"));
//        assertEquals("Usuário com o email [email] não foi encontrado", result.getMessage());
//        assertEquals(org.springframework.http.HttpStatus.NOT_FOUND, result.getHttpStatusCode());
//    }
//
}